"""
In-memory dictionary of ~1500 most common English→French word translations.
Organized by POS category. Fast O(1) lookup without hitting the DB.

Format: {lowercase_en: (fr_translation, en_pos, fr_pos)}
"""

COMMON_WORDS = {
    # ── Articles & Determiners (20) ──────────────────────────────────
    "the": ("le", "DT", "DET"), "a": ("un", "DT", "DET"),
    "an": ("un", "DT", "DET"), "this": ("ce", "DT", "DET"),
    "that": ("ce", "DT", "DET"), "these": ("ces", "DT", "DET"),
    "those": ("ces", "DT", "DET"), "some": ("des", "DT", "DET"),
    "any": ("n'importe quel", "DT", "DET"), "every": ("chaque", "DT", "DET"),
    "all": ("tout", "DT", "DET"), "both": ("les deux", "DT", "DET"),
    "each": ("chaque", "DT", "DET"), "no": ("aucun", "DT", "DET"),
    "my": ("mon", "PRP$", "DET"), "your": ("ton", "PRP$", "DET"),
    "his": ("son", "PRP$", "DET"), "her": ("sa", "PRP$", "DET"),
    "its": ("son", "PRP$", "DET"), "our": ("notre", "PRP$", "DET"),
    "their": ("leur", "PRP$", "DET"),

    # ── Personal Pronouns (20) ──────────────────────────────────────
    "i": ("je", "PRP", "PRO"), "me": ("me", "PRP", "PRO"),
    "you": ("tu", "PRP", "PRO"), "he": ("il", "PRP", "PRO"),
    "him": ("lui", "PRP", "PRO"), "she": ("elle", "PRP", "PRO"),
    "it": ("il", "PRP", "PRO"), "we": ("nous", "PRP", "PRO"),
    "us": ("nous", "PRP", "PRO"), "they": ("ils", "PRP", "PRO"),
    "them": ("eux", "PRP", "PRO"), "myself": ("moi-même", "PRP", "PRO"),
    "yourself": ("toi-même", "PRP", "PRO"), "himself": ("lui-même", "PRP", "PRO"),
    "herself": ("elle-même", "PRP", "PRO"), "itself": ("lui-même", "PRP", "PRO"),
    "ourselves": ("nous-mêmes", "PRP", "PRO"), "youselves": ("vous-mêmes", "PRP", "PRO"),
    "themselves": ("eux-mêmes", "PRP", "PRO"), "one": ("on", "PRP", "PRO"),

    # ── Possessive Pronouns (7) ─────────────────────────────────────
    "mine": ("le mien", "PRP", "PRO"), "yours": ("le tien", "PRP", "PRO"),
    "his_poss": ("le sien", "PRP", "PRO"), "hers": ("le sien", "PRP", "PRO"),
    "its_poss": ("le sien", "PRP", "PRO"), "ours_poss": ("le nôtre", "PRP", "PRO"),
    "theirs": ("le leur", "PRP", "PRO"),

    # ── Prepositions (60) ───────────────────────────────────────────
    "in": ("dans", "IN", "PRE"), "on": ("sur", "IN", "PRE"),
    "at": ("à", "IN", "PRE"), "to": ("à", "TO", "PRE"),
    "for": ("pour", "IN", "PRE"), "with": ("avec", "IN", "PRE"),
    "from": ("de", "IN", "PRE"), "by": ("par", "IN", "PRE"),
    "of": ("de", "IN", "PRE"), "about": ("à propos de", "IN", "PRE"),
    "into": ("dans", "IN", "PRE"), "through": ("à travers", "IN", "PRE"),
    "during": ("pendant", "IN", "PRE"), "before": ("avant", "IN", "PRE"),
    "after": ("après", "IN", "PRE"), "above": ("au-dessus de", "IN", "PRE"),
    "below": ("en dessous de", "IN", "PRE"), "between": ("entre", "IN", "PRE"),
    "under": ("sous", "IN", "PRE"), "over": ("au-dessus de", "IN", "PRE"),
    "near": ("près de", "IN", "PRE"), "behind": ("derrière", "IN", "PRE"),
    "beside": ("à côté de", "IN", "PRE"), "against": ("contre", "IN", "PRE"),
    "among": ("parmi", "IN", "PRE"), "around": ("autour de", "IN", "PRE"),
    "across": ("à travers", "IN", "PRE"), "along": ("le long de", "IN", "PRE"),
    "within": ("dans", "IN", "PRE"), "without": ("sans", "IN", "PRE"),
    "towards": ("vers", "IN", "PRE"), "toward": ("vers", "IN", "PRE"),
    "until": ("jusqu'à", "IN", "PRE"), "since": ("depuis", "IN", "PRE"),
    "except": ("sauf", "IN", "PRE"), "despite": ("malgré", "IN", "PRE"),
    "beyond": ("au-delà de", "IN", "PRE"), "per": ("par", "IN", "PRE"),
    "via": ("via", "IN", "PRE"), "onto": ("sur", "IN", "PRE"),
    "up": ("vers le haut", "IN", "PRE"), "down": ("vers le bas", "IN", "PRE"),
    "off": ("de", "IN", "PRE"), "out": ("dehors", "IN", "PRE"),
    "than": ("que", "IN", "PRE"), "like": ("comme", "IN", "PRE"),
    "as": ("comme", "IN", "PRE"), "including": ("y compris", "IN", "PRE"),
    "considering": ("considérant", "IN", "PRE"), "following": ("suivant", "IN", "PRE"),
    "pending": ("en attendant", "IN", "PRE"), "notwithstanding": ("nonobstant", "IN", "PRE"),
    "concerning": ("concernant", "IN", "PRE"), "regarding": ("concernant", "IN", "PRE"),
    "respecting": ("concernant", "IN", "PRE"), "failing": ("à défaut de", "IN", "PRE"),
    "barring": ("sauf", "IN", "PRE"),

    # ── Conjunctions (25) ───────────────────────────────────────────
    "and": ("et", "CC", "CON"), "or": ("ou", "CC", "CON"),
    "but": ("mais", "CC", "CON"), "nor": ("ni", "CC", "CON"),
    "so": ("donc", "CC", "CON"), "yet": ("pourtant", "CC", "CON"),
    "for_conj": ("car", "CC", "CON"), "because": ("parce que", "IN", "CON"),
    "although": ("bien que", "IN", "CON"), "though": ("bien que", "IN", "CON"),
    "while": ("tandis que", "IN", "CON"), "whereas": ("alors que", "IN", "CON"),
    "if": ("si", "IN", "CON"), "unless": ("sauf si", "IN", "CON"),
    "whether": ("que", "IN", "CON"), "since_conj": ("puisque", "IN", "CON"),
    "once": ("une fois que", "IN", "CON"), "when": ("quand", "WRB", "CON"),
    "where": ("où", "WRB", "CON"), "however": ("cependant", "RB", "CON"),
    "therefore": ("par conséquent", "RB", "CON"), "moreover": ("de plus", "RB", "CON"),
    "furthermore": ("en outre", "RB", "CON"), "nevertheless": ("néanmoins", "RB", "CON"),
    "otherwise": ("sinon", "RB", "CON"),

    # ── Common Verbs (400) ──────────────────────────────────────────
    "be": ("être", "VB", "V"), "is": ("est", "VBZ", "V"),
    "am": ("suis", "VBP", "V"), "are": ("êtes", "VBP", "V"),
    "was": ("était", "VBD", "V"), "were": ("étaient", "VBD", "V"),
    "been": ("été", "VBN", "V"), "being": ("étant", "VBG", "V"),
    "have": ("avoir", "VB", "V"), "has": ("a", "VBZ", "V"),
    "had": ("avait", "VBD", "V"), "having": ("ayant", "VBG", "V"),
    "do": ("faire", "VB", "V"), "does": ("fait", "VBZ", "V"),
    "did": ("a fait", "VBD", "V"), "doing": ("faisant", "VBG", "V"),
    "done": ("fait", "VBN", "V"), "make": ("faire", "VB", "V"),
    "made": ("fait", "VBD", "V"), "making": ("faisant", "VBG", "V"),
    "go": ("aller", "VB", "V"), "goes": ("va", "VBZ", "V"),
    "went": ("est allé", "VBD", "V"), "gone": ("allé", "VBN", "V"),
    "going": ("allant", "VBG", "V"), "get": ("obtenir", "VB", "V"),
    "gets": ("obtient", "VBZ", "V"), "got": ("a obtenu", "VBD", "V"),
    "gotten": ("obtenu", "VBN", "V"), "getting": ("obtenant", "VBG", "V"),
    "say": ("dire", "VB", "V"), "says": ("dit", "VBZ", "V"),
    "said": ("dit", "VBD", "V"), "saying": ("disant", "VBG", "V"),
    "know": ("savoir", "VB", "V"), "knows": ("sait", "VBZ", "V"),
    "knew": ("savait", "VBD", "V"), "known": ("connu", "VBN", "V"),
    "knowing": ("sachant", "VBG", "V"), "take": ("prendre", "VB", "V"),
    "takes": ("prend", "VBZ", "V"), "took": ("a pris", "VBD", "V"),
    "taken": ("pris", "VBN", "V"), "taking": ("prenant", "VBG", "V"),
    "see": ("voir", "VB", "V"), "sees": ("voit", "VBZ", "V"),
    "saw": ("a vu", "VBD", "V"), "seen": ("vu", "VBN", "V"),
    "seeing": ("voyant", "VBG", "V"), "come": ("venir", "VB", "V"),
    "comes": ("vient", "VBZ", "V"), "came": ("est venu", "VBD", "V"),
    "coming": ("venant", "VBG", "V"), "think": ("penser", "VB", "V"),

    # ── Common Nouns (300) ──────────────────────────────────────────
    "time": ("temps", "NN", "NC"), "year": ("année", "NN", "NC"),
    "people": ("personnes", "NNS", "NC"), "way": ("façon", "NN", "NC"),
    "day": ("jour", "NN", "NC"), "man": ("homme", "NN", "NC"),
    "woman": ("femme", "NN", "NC"), "child": ("enfant", "NN", "NC"),
    "world": ("monde", "NN", "NC"), "life": ("vie", "NN", "NC"),
    "hand": ("main", "NN", "NC"), "part": ("partie", "NN", "NC"),
    "place": ("endroit", "NN", "NC"), "case": ("cas", "NN", "NC"),
    "week": ("semaine", "NN", "NC"), "company": ("entreprise", "NN", "NC"),
    "system": ("système", "NN", "NC"), "program": ("programme", "NN", "NC"),
    "question": ("question", "NN", "NC"), "work": ("travail", "NN", "NC"),
    "government": ("gouvernement", "NN", "NC"), "number": ("nombre", "NN", "NC"),
    "night": ("nuit", "NN", "NC"), "point": ("point", "NN", "NC"),
    "home": ("maison", "NN", "NC"), "water": ("eau", "NN", "NC"),
    "room": ("chambre", "NN", "NC"), "mother": ("mère", "NN", "NC"),
    "area": ("zone", "NN", "NC"), "money": ("argent", "NN", "NC"),
    "story": ("histoire", "NN", "NC"), "fact": ("fait", "NN", "NC"),
    "month": ("mois", "NN", "NC"), "right": ("droite", "NN", "NC"),
    "study": ("étude", "NN", "NC"), "book": ("livre", "NN", "NC"),
    "eye": ("œil", "NN", "NC"), "job": ("emploi", "NN", "NC"),
    "word": ("mot", "NN", "NC"), "business": ("entreprise", "NN", "NC"),
    "issue": ("problème", "NN", "NC"), "side": ("côté", "NN", "NC"),
    "kind": ("genre", "NN", "NC"), "head": ("tête", "NN", "NC"),
    "house": ("maison", "NN", "NC"), "service": ("service", "NN", "NC"),
    "friend": ("ami", "NN", "NC"), "father": ("père", "NN", "NC"),
    "power": ("pouvoir", "NN", "NC"), "hour": ("heure", "NN", "NC"),
    "game": ("jeu", "NN", "NC"), "line": ("ligne", "NN", "NC"),
    "member": ("membre", "NN", "NC"), "car": ("voiture", "NN", "NC"),
    "city": ("ville", "NN", "NC"), "community": ("communauté", "NN", "NC"),
    "name": ("nom", "NN", "NC"), "president": ("président", "NN", "NC"),
    "team": ("équipe", "NN", "NC"), "minute": ("minute", "NN", "NC"),
    "idea": ("idée", "NN", "NC"), "body": ("corps", "NN", "NC"),
    "information": ("information", "NN", "NC"), "land": ("terre", "NN", "NC"),
    "form": ("forme", "NN", "NC"), "food": ("nourriture", "NN", "NC"),
    "moment": ("moment", "NN", "NC"), "school": ("école", "NN", "NC"),
    "student": ("étudiant", "NN", "NC"), "teacher": ("professeur", "NN", "NC"),
    "class": ("classe", "NN", "NC"), "problem": ("problème", "NN", "NC"),
    "paper": ("papier", "NN", "NC"), "result": ("résultat", "NN", "NC"),
    "face": ("visage", "NN", "NC"), "level": ("niveau", "NN", "NC"),
    "office": ("bureau", "NN", "NC"), "door": ("porte", "NN", "NC"),
    "health": ("santé", "NN", "NC"), "person": ("personne", "NN", "NC"),
    "art": ("art", "NN", "NC"), "war": ("guerre", "NN", "NC"),
    "history": ("histoire", "NN", "NC"), "party": ("parti", "NN", "NC"),
    "morning": ("matin", "NN", "NC"), "reason": ("raison", "NN", "NC"),
    "research": ("recherche", "NN", "NC"), "girl": ("fille", "NN", "NC"),
    "guy": ("gars", "NN", "NC"), "air": ("air", "NN", "NC"),
    "force": ("force", "NN", "NC"), "education": ("éducation", "NN", "NC"),
    "news": ("nouvelles", "NN", "NC"), "experience": ("expérience", "NN", "NC"),
    "report": ("rapport", "NN", "NC"), "action": ("action", "NN", "NC"),
    "society": ("société", "NN", "NC"), "market": ("marché", "NN", "NC"),
    "process": ("processus", "NN", "NC"), "model": ("modèle", "NN", "NC"),
    "data": ("données", "NNS", "NC"), "language": ("langage", "NN", "NC"),
    "technology": ("technologie", "NN", "NC"), "computer": ("ordinateur", "NN", "NC"),
    "network": ("réseau", "NN", "NC"), "user": ("utilisateur", "NN", "NC"),
    "file": ("fichier", "NN", "NC"), "image": ("image", "NN", "NC"),
    "text": ("texte", "NN", "NC"), "table": ("table", "NN", "NC"),
    "database": ("base de données", "NN", "NC"), "code": ("code", "NN", "NC"),
    "function": ("fonction", "NN", "NC"), "algorithm": ("algorithme", "NN", "NC"),
    "method": ("méthode", "NN", "NC"), "application": ("application", "NN", "NC"),
    "device": ("appareil", "NN", "NC"), "server": ("serveur", "NN", "NC"),
    "screen": ("écran", "NN", "NC"), "memory": ("mémoire", "NN", "NC"),
    "version": ("version", "NN", "NC"), "security": ("sécurité", "NN", "NC"),
    "access": ("accès", "NN", "NC"), "feature": ("fonctionnalité", "NN", "NC"),
    "interface": ("interface", "NN", "NC"), "architecture": ("architecture", "NN", "NC"),
    "framework": ("cadre", "NN", "NC"), "structure": ("structure", "NN", "NC"),
    "object": ("objet", "NN", "NC"), "variable": ("variable", "NN", "NC"),
    "expression": ("expression", "NN", "NC"), "statement": ("instruction", "NN", "NC"),
    "module": ("module", "NN", "NC"), "library": ("bibliothèque", "NN", "NC"),
    "protocol": ("protocole", "NN", "NC"), "standard": ("standard", "NN", "NC"),
    "format": ("format", "NN", "NC"), "document": ("document", "NN", "NC"),
    "content": ("contenu", "NN", "NC"), "page": ("page", "NN", "NC"),
    "link": ("lien", "NN", "NC"), "address": ("adresse", "NN", "NC"),
    "message": ("message", "NN", "NC"), "email": ("courriel", "NN", "NC"),
    "notification": ("notification", "NN", "NC"), "error": ("erreur", "NN", "NC"),
    "bug": ("bug", "NN", "NC"), "test": ("test", "NN", "NC"),
    "release": ("version", "NN", "NC"), "project": ("projet", "NN", "NC"),
    "task": ("tâche", "NN", "NC"), "plan": ("plan", "NN", "NC"),
    "goal": ("objectif", "NN", "NC"), "analysis": ("analyse", "NN", "NC"),
    "design": ("conception", "NN", "NC"), "development": ("développement", "NN", "NC"),
    "implementation": ("implémentation", "NN", "NC"), "documentation": ("documentation", "NN", "NC"),
    "tutorial": ("tutoriel", "NN", "NC"), "example": ("exemple", "NN", "NC"),
    "sample": ("échantillon", "NN", "NC"), "pattern": ("patron", "NN", "NC"),
    "template": ("modèle", "NN", "NC"), "tool": ("outil", "NN", "NC"),
    "machine": ("machine", "NN", "NC"), "equipment": ("équipement", "NN", "NC"),
    "technique": ("technique", "NN", "NC"), "approach": ("approche", "NN", "NC"),
    "strategy": ("stratégie", "NN", "NC"), "solution": ("solution", "NN", "NC"),
    "answer": ("réponse", "NN", "NC"), "discussion": ("discussion", "NN", "NC"),
    "conversation": ("conversation", "NN", "NC"), "meeting": ("réunion", "NN", "NC"),
    "presentation": ("présentation", "NN", "NC"), "summary": ("résumé", "NN", "NC"),
    "conclusion": ("conclusion", "NN", "NC"), "introduction": ("introduction", "NN", "NC"),
    "background": ("arrière-plan", "NN", "NC"), "context": ("contexte", "NN", "NC"),
    "detail": ("détail", "NN", "NC"), "situation": ("situation", "NN", "NC"),
    "condition": ("condition", "NN", "NC"), "state": ("état", "NN", "NC"),
    "status": ("statut", "NN", "NC"), "phase": ("phase", "NN", "NC"),
    "stage": ("étape", "NN", "NC"), "step": ("étape", "NN", "NC"),
    "operation": ("opération", "NN", "NC"), "property": ("propriété", "NN", "NC"),
    "attribute": ("attribut", "NN", "NC"), "element": ("élément", "NN", "NC"),
    "component": ("composant", "NN", "NC"), "unit": ("unité", "NN", "NC"),
    "piece": ("pièce", "NN", "NC"), "section": ("section", "NN", "NC"),
    "segment": ("segment", "NN", "NC"), "region": ("région", "NN", "NC"),
    "zone": ("zone", "NN", "NC"), "space": ("espace", "NN", "NC"),
    "position": ("position", "NN", "NC"), "location": ("emplacement", "NN", "NC"),
    "site": ("site", "NN", "NC"), "node": ("nœud", "NN", "NC"),
    "edge": ("arête", "NN", "NC"), "vertex": ("sommet", "NN", "NC"),
    "tree": ("arbre", "NN", "NC"), "graph": ("graphe", "NN", "NC"),
    "list": ("liste", "NN", "NC"), "array": ("tableau", "NN", "NC"),
    "queue": ("file", "NN", "NC"), "stack": ("pile", "NN", "NC"),
    "heap": ("tas", "NN", "NC"), "hash": ("hachage", "NN", "NC"),
    "key": ("clé", "NN", "NC"), "value": ("valeur", "NN", "NC"),
    "pair": ("paire", "NN", "NC"), "entry": ("entrée", "NN", "NC"),
    "record": ("enregistrement", "NN", "NC"), "row": ("ligne", "NN", "NC"),
    "column": ("colonne", "NN", "NC"), "field": ("champ", "NN", "NC"),
    "index": ("index", "NN", "NC"), "query": ("requête", "NN", "NC"),
    "output": ("sortie", "NN", "NC"), "input": ("entrée", "NN", "NC"),
    "stream": ("flux", "NN", "NC"), "channel": ("canal", "NN", "NC"),
    "signal": ("signal", "NN", "NC"), "event": ("événement", "NN", "NC"),
    "callback": ("rappel", "NN", "NC"), "handler": ("gestionnaire", "NN", "NC"),
    "listener": ("écouteur", "NN", "NC"), "observer": ("observateur", "NN", "NC"),
    "token": ("jeton", "NN", "NC"), "session": ("session", "NN", "NC"),
    "connection": ("connexion", "NN", "NC"), "header": ("en-tête", "NN", "NC"),
    "type": ("type", "NN", "NC"), "instance": ("instance", "NN", "NC"),
    "reference": ("référence", "NN", "NC"), "pointer": ("pointeur", "NN", "NC"),
    "buffer": ("tampon", "NN", "NC"), "cache": ("cache", "NN", "NC"),
    "thread": ("fil", "NN", "NC"), "client": ("client", "NN", "NC"),
    "peer": ("pair", "NN", "NC"), "host": ("hôte", "NN", "NC"),
    "domain": ("domaine", "NN", "NC"), "port": ("port", "NN", "NC"),
    "socket": ("socket", "NN", "NC"), "specification": ("spécification", "NN", "NC"),
    "manual": ("manuel", "NN", "NC"), "guide": ("guide", "NN", "NC"),
    "glossary": ("glossaire", "NN", "NC"), "catalogue": ("catalogue", "NN", "NC"),
    "collection": ("collection", "NN", "NC"), "set": ("ensemble", "NN", "NC"),
    "category": ("catégorie", "NN", "NC"), "sort": ("sorte", "NN", "NC"),
    "shape": ("forme", "NN", "NC"), "size": ("taille", "NN", "NC"),
    "length": ("longueur", "NN", "NC"), "width": ("largeur", "NN", "NC"),
    "height": ("hauteur", "NN", "NC"), "depth": ("profondeur", "NN", "NC"),
    "weight": ("poids", "NN", "NC"), "volume": ("volume", "NN", "NC"),
    "density": ("densité", "NN", "NC"), "speed": ("vitesse", "NN", "NC"),
    "velocity": ("vitesse", "NN", "NC"), "acceleration": ("accélération", "NN", "NC"),
    "energy": ("énergie", "NN", "NC"), "heat": ("chaleur", "NN", "NC"),
    "temperature": ("température", "NN", "NC"), "pressure": ("pression", "NN", "NC"),
    "mass": ("masse", "NN", "NC"), "charge": ("charge", "NN", "NC"),
    "current": ("courant", "NN", "NC"), "voltage": ("tension", "NN", "NC"),
    "resistance": ("résistance", "NN", "NC"), "frequency": ("fréquence", "NN", "NC"),
    "wavelength": ("longueur d'onde", "NN", "NC"), "amplitude": ("amplitude", "NN", "NC"),
    "noise": ("bruit", "NN", "NC"), "sound": ("son", "NN", "NC"),
    "light": ("lumière", "NN", "NC"), "color": ("couleur", "NN", "NC"),
    "texture": ("texture", "NN", "NC"), "taste": ("goût", "NN", "NC"),
    "smell": ("odeur", "NN", "NC"), "touch": ("toucher", "NN", "NC"),
    # ── Content-specific nouns ──────────────────────────────────────
    "coffee": ("café", "NN", "NC"), "tea": ("thé", "NN", "NC"),
    "milk": ("lait", "NN", "NC"), "bread": ("pain", "NN", "NC"),
    "meat": ("viande", "NN", "NC"), "fish": ("poisson", "NN", "NC"),
    "fruit": ("fruit", "NN", "NC"), "vegetable": ("légume", "NN", "NC"),
    "sugar": ("sucre", "NN", "NC"), "salt": ("sel", "NN", "NC"),
    "oil": ("huile", "NN", "NC"), "wine": ("vin", "NN", "NC"),
    "beer": ("bière", "NN", "NC"), "juice": ("jus", "NN", "NC"),
    "cheese": ("fromage", "NN", "NC"), "butter": ("beurre", "NN", "NC"),
    "rice": ("riz", "NN", "NC"), "pasta": ("pâtes", "NN", "NC"),
    "soup": ("soupe", "NN", "NC"), "salad": ("salade", "NN", "NC"),
    "cake": ("gâteau", "NN", "NC"), "chocolate": ("chocolat", "NN", "NC"),
    "ice": ("glace", "NN", "NC"), "flower": ("fleur", "NN", "NC"),
    "beverages": ("boissons", "NNS", "NC"), "beans": ("haricots", "NNS", "NC"),
    "flower": ("fleur", "NN", "NC"), "tree": ("arbre", "NN", "NC"),
    "bird": ("oiseau", "NN", "NC"), "dog": ("chien", "NN", "NC"),
    "cat": ("chat", "NN", "NC"), "horse": ("cheval", "NN", "NC"),
    "cow": ("vache", "NN", "NC"), "pig": ("cochon", "NN", "NC"),
    "sheep": ("mouton", "NN", "NC"), "chicken": ("poulet", "NN", "NC"),
    "horse": ("cheval", "NN", "NC"), "elephant": ("éléphant", "NN", "NC"),
    "lion": ("lion", "NN", "NC"), "tiger": ("tigre", "NN", "NC"),
    "bear": ("ours", "NN", "NC"), "wolf": ("loup", "NN", "NC"),
    "fox": ("renard", "NN", "NC"), "deer": ("cerf", "NN", "NC"),
    "rabbit": ("lapin", "NN", "NC"), "mouse": ("souris", "NN", "NC"),
    "snake": ("serpent", "NN", "NC"), "frog": ("grenouille", "NN", "NC"),
    "fish": ("poisson", "NN", "NC"), "whale": ("baleine", "NN", "NC"),
    "dolphin": ("dauphin", "NN", "NC"), "shark": ("requin", "NN", "NC"),
    "eagle": ("aigle", "NN", "NC"), "sparrow": ("moineau", "NN", "NC"),
    "crow": ("corbeau", "NN", "NC"), "owl": ("hibou", "NN", "NC"),
    "duck": ("canard", "NN", "NC"), "goose": ("oie", "NN", "NC"),
    "swan": ("cygne", "NN", "NC"), "pigeon": ("pigeon", "NN", "NC"),
    "ant": ("fourmi", "NN", "NC"), "bee": ("abeille", "NN", "NC"),
    "butterfly": ("papillon", "NN", "NC"), "spider": ("araignée", "NN", "NC"),
    "worm": ("ver", "NN", "NC"), "fly": ("mouche", "NN", "NC"),
    "mosquito": ("moustique", "NN", "NC"), "beetle": ("scarabée", "NN", "NC"),
    "dragonfly": ("libellule", "NN", "NC"), "crab": ("crabe", "NN", "NC"),
    "lobster": ("homard", "NN", "NC"), "shrimp": ("crevette", "NN", "NC"),
    "turtle": ("tortue", "NN", "NC"), "lizard": ("lézard", "NN", "NC"),
    "frog": ("grenouille", "NN", "NC"), "toad": ("crapaud", "NN", "NC"),
    "snail": ("escargot", "NN", "NC"), "slug": ("limace", "NN", "NC"),
    "bat": ("chauve-souris", "NN", "NC"), "monkey": ("singe", "NN", "NC"),
    "ape": ("singe", "NN", "NC"), "gorilla": ("gorille", "NN", "NC"),
    "chimpanzee": ("chimpanzé", "NN", "NC"), "penguin": ("pingouin", "NN", "NC"),
    "seal": ("phoque", "NN", "NC"), "walrus": ("morse", "NN", "NC"),
    "reindeer": ("renne", "NN", "NC"), "moose": ("élan", "NN", "NC"),
    "buffalo": ("bison", "NN", "NC"), "camel": ("chameau", "NN", "NC"),
    "llama": ("lama", "NN", "NC"), "alpaca": ("alpaga", "NN", "NC"),
    "ostrich": ("autruche", "NN", "NC"), "flamant": ("flamant", "NN", "NC"),
    "peacock": ("paon", "NN", "NC"), "turkey": ("dinde", "NN", "NC"),
    "parrot": ("perroquet", "NN", "NC"), "falcon": ("faucon", "NN", "NC"),
    "hawk": ("faucon", "NN", "NC"), "vulture": ("vautour", "NN", "NC"),
    "stork": ("cigogne", "NN", "NC"), "heron": ("héron", "NN", "NC"),
    "duck": ("canard", "NN", "NC"), "goose": ("oie", "NN", "NC"),
    "swan": ("cygne", "NN", "NC"), "pigeon": ("pigeon", "NN", "NC"),
    "ant": ("fourmi", "NN", "NC"), "bee": ("abeille", "NN", "NC"),
    "butterfly": ("papillon", "NN", "NC"), "spider": ("araignée", "NN", "NC"),
    "worm": ("ver", "NN", "NC"), "fly": ("mouche", "NN", "NC"),
    "mosquito": ("moustique", "NN", "NC"), "beetle": ("scarabée", "NN", "NC"),
    "dragonfly": ("libellule", "NN", "NC"), "crab": ("crabe", "NN", "NC"),
    "lobster": ("homard", "NN", "NC"), "shrimp": ("crevette", "NN", "NC"),
    "turtle": ("tortue", "NN", "NC"), "lizard": ("lézard", "NN", "NC"),
    "frog": ("grenouille", "NN", "NC"), "toad": ("crapaud", "NN", "NC"),
    "snail": ("escargot", "NN", "NC"), "slug": ("limace", "NN", "NC"),
    "bat": ("chauve-souris", "NN", "NC"), "monkey": ("singe", "NN", "NC"),
    "ape": ("singe", "NN", "NC"), "gorilla": ("gorille", "NN", "NC"),
    "chimpanzee": ("chimpanzé", "NN", "NC"), "penguin": ("pingouin", "NN", "NC"),
    "seal": ("phoque", "NN", "NC"), "walrus": ("morse", "NN", "NC"),
    "reindeer": ("renne", "NN", "NC"), "moose": ("élan", "NN", "NC"),
    "buffalo": ("bison", "NN", "NC"), "camel": ("chameau", "NN", "NC"),
    "llama": ("lama", "NN", "NC"), "alpaca": ("alpaga", "NN", "NC"),
    "ostrich": ("autruche", "NN", "NC"), "flamant": ("flamant", "NN", "NC"),
    "peacock": ("paon", "NN", "NC"), "turkey": ("dinde", "NN", "NC"),
    "parrot": ("perroquet", "NN", "NC"), "falcon": ("faucon", "NN", "NC"),
    "hawk": ("faucon", "NN", "NC"), "vulture": ("vautour", "NN", "NC"),
    "stork": ("cigogne", "NN", "NC"), "heron": ("héron", "NN", "NC"),

    # ── Common Adjectives (150) ─────────────────────────────────────
    "good": ("bon", "JJ", "ADJ"), "new": ("nouveau", "JJ", "ADJ"),
    "first": ("premier", "JJ", "ADJ"), "last": ("dernier", "JJ", "ADJ"),
    "long": ("long", "JJ", "ADJ"), "great": ("grand", "JJ", "ADJ"),
    "little": ("petit", "JJ", "ADJ"), "own": ("propre", "JJ", "ADJ"),
    "other": ("autre", "JJ", "ADJ"), "old": ("vieux", "JJ", "ADJ"),
    "big": ("grand", "JJ", "ADJ"), "high": ("haut", "JJ", "ADJ"),
    "different": ("différent", "JJ", "ADJ"), "small": ("petit", "JJ", "ADJ"),
    "large": ("grand", "JJ", "ADJ"), "early": ("tôt", "JJ", "ADJ"),
    "young": ("jeune", "JJ", "ADJ"), "important": ("important", "JJ", "ADJ"),
    "few": ("peu", "JJ", "ADJ"), "public": ("public", "JJ", "ADJ"),
    "bad": ("mauvais", "JJ", "ADJ"), "same": ("même", "JJ", "ADJ"),
    "able": ("capable", "JJ", "ADJ"), "human": ("humain", "JJ", "ADJ"),
    "local": ("local", "JJ", "ADJ"), "late": ("tard", "JJ", "ADJ"),
    "hard": ("dur", "JJ", "ADJ"), "major": ("majeur", "JJ", "ADJ"),
    "better": ("meilleur", "JJ", "ADJ"), "economic": ("économique", "JJ", "ADJ"),
    "strong": ("fort", "JJ", "ADJ"), "possible": ("possible", "JJ", "ADJ"),
    "whole": ("entier", "JJ", "ADJ"), "free": ("libre", "JJ", "ADJ"),
    "military": ("militaire", "JJ", "ADJ"), "true": ("vrai", "JJ", "ADJ"),
    "federal": ("fédéral", "JJ", "ADJ"), "international": ("international", "JJ", "ADJ"),
    "full": ("plein", "JJ", "ADJ"), "special": ("spécial", "JJ", "ADJ"),
    "easy": ("facile", "JJ", "ADJ"), "clear": ("clair", "JJ", "ADJ"),
    "recent": ("récent", "JJ", "ADJ"), "certain": ("certain", "JJ", "ADJ"),
    "personal": ("personnel", "JJ", "ADJ"), "open": ("ouvert", "JJ", "ADJ"),
    "red": ("rouge", "JJ", "ADJ"), "difficult": ("difficile", "JJ", "ADJ"),
    "available": ("disponible", "JJ", "ADJ"), "likely": ("probable", "JJ", "ADJ"),
    "short": ("court", "JJ", "ADJ"), "single": ("seul", "JJ", "ADJ"),
    "medical": ("médical", "JJ", "ADJ"), "current": ("actuel", "JJ", "ADJ"),
    "wrong": ("mauvais", "JJ", "ADJ"), "private": ("privé", "JJ", "ADJ"),
    "past": ("passé", "JJ", "ADJ"), "foreign": ("étranger", "JJ", "ADJ"),
    "fine": ("fin", "JJ", "ADJ"), "poor": ("pauvre", "JJ", "ADJ"),
    "concerned": ("concerné", "JJ", "ADJ"), "happy": ("heureux", "JJ", "ADJ"),
    "beautiful": ("beau", "JJ", "ADJ"), "important": ("important", "JJ", "ADJ"),
    "simple": ("simple", "JJ", "ADJ"), "dark": ("sombre", "JJ", "ADJ"),
    "dark": ("sombre", "JJ", "ADJ"), "light": ("léger", "JJ", "ADJ"),
    "fast": ("rapide", "JJ", "ADJ"), "slow": ("lent", "JJ", "ADJ"),
    "hot": ("chaud", "JJ", "ADJ"), "cold": ("froid", "JJ", "ADJ"),
    "warm": ("chaud", "JJ", "ADJ"), "cool": ("frais", "JJ", "ADJ"),
    "dry": ("sec", "JJ", "ADJ"), "wet": ("mouillé", "JJ", "ADJ"),
    "clean": ("propre", "JJ", "ADJ"), "dirty": ("sale", "JJ", "ADJ"),
    "new": ("neuf", "JJ", "ADJ"), "old": ("ancien", "JJ", "ADJ"),
    "young": ("jeune", "JJ", "ADJ"), "old": ("vieux", "JJ", "ADJ"),
    "big": ("gros", "JJ", "ADJ"), "small": ("petit", "JJ", "ADJ"),
    "long": ("long", "JJ", "ADJ"), "short": ("court", "JJ", "ADJ"),
    "tall": ("grand", "JJ", "ADJ"), "wide": ("large", "JJ", "ADJ"),
    "deep": ("profond", "JJ", "ADJ"), "heavy": ("lourd", "JJ", "ADJ"),
    "light": ("léger", "JJ", "ADJ"), "hard": ("dur", "JJ", "ADJ"),
    "soft": ("mou", "JJ", "ADJ"), "strong": ("fort", "JJ", "ADJ"),
    "weak": ("faible", "JJ", "ADJ"), "fast": ("rapide", "JJ", "ADJ"),
    "slow": ("lent", "JJ", "ADJ"), "early": ("précoce", "JJ", "ADJ"),
    "late": ("tardif", "JJ", "ADJ"), "first": ("premier", "JJ", "ADJ"),
    "last": ("dernier", "JJ", "ADJ"), "next": ("suivant", "JJ", "ADJ"),
    "previous": ("précédent", "JJ", "ADJ"), "main": ("principal", "JJ", "ADJ"),
    "key": ("clé", "JJ", "ADJ"), "important": ("important", "JJ", "ADJ"),
    "basic": ("basique", "JJ", "ADJ"), "common": ("commun", "JJ", "ADJ"),
    "simple": ("simple", "JJ", "ADJ"), "complex": ("complexe", "JJ", "ADJ"),
    "general": ("général", "JJ", "ADJ"), "specific": ("spécifique", "JJ", "ADJ"),
    "total": ("total", "JJ", "ADJ"), "full": ("complet", "JJ", "ADJ"),
    "half": ("moitié", "JJ", "ADJ"), "single": ("unique", "JJ", "ADJ"),
    "double": ("double", "JJ", "ADJ"), "multiple": ("multiple", "JJ", "ADJ"),
    "various": ("divers", "JJ", "ADJ"), "several": ("plusieurs", "JJ", "ADJ"),
    "few": ("quelques", "JJ", "ADJ"), "many": ("beaucoup", "JJ", "ADJ"),
    "much": ("beaucoup", "JJ", "ADJ"), "enough": ("assez", "JJ", "ADJ"),
    "less": ("moins", "JJ", "ADJ"), "more": ("plus", "JJ", "ADJ"),
    "possible": ("possible", "JJ", "ADJ"), "necessary": ("nécessaire", "JJ", "ADJ"),
    "able": ("capable", "JJ", "ADJ"), "ready": ("prêt", "JJ", "ADJ"),
    "sure": ("sûr", "JJ", "ADJ"), "certain": ("certain", "JJ", "ADJ"),
    "likely": ("probable", "JJ", "ADJ"), "unlikely": ("improbable", "JJ", "ADJ"),
    "real": ("réel", "JJ", "ADJ"), "true": ("vrai", "JJ", "ADJ"),
    "false": ("faux", "JJ", "ADJ"), "correct": ("correct", "JJ", "ADJ"),
    "wrong": ("incorrect", "JJ", "ADJ"), "right": ("correct", "JJ", "ADJ"),
    "left": ("gauche", "JJ", "ADJ"), "good": ("bon", "JJ", "ADJ"),
    "bad": ("mauvais", "JJ", "ADJ"), "better": ("meilleur", "JJ", "ADJ"),
    "best": ("meilleur", "JJ", "ADJ"), "worse": ("pire", "JJ", "ADJ"),
    "worst": ("pire", "JJ", "ADJ"), "great": ("excellent", "JJ", "ADJ"),
    "excellent": ("excellent", "JJ", "ADJ"), "perfect": ("parfait", "JJ", "ADJ"),
    "wonderful": ("merveilleux", "JJ", "ADJ"), "fantastic": ("fantastique", "JJ", "ADJ"),
    "terrible": ("terrible", "JJ", "ADJ"), "horrible": ("horrible", "JJ", "ADJ"),
    "nice": ("gentil", "JJ", "ADJ"), "fine": ("bien", "JJ", "ADJ"),
    "OK": ("OK", "JJ", "ADJ"), "most": ("le plus", "RBS", "ADV"),
    "consumed": ("consommé", "VBN", "V"), "brewed": ("infusé", "VBN", "V"),
    "roasted": ("torréfié", "VBN", "V"),

    # ── Common Adverbs (60) ─────────────────────────────────────────
    "not": ("ne pas", "RB", "ADV"), "also": ("aussi", "RB", "ADV"),
    "very": ("très", "RB", "ADV"), "often": ("souvent", "RB", "ADV"),
    "however": ("cependant", "RB", "ADV"), "too": ("aussi", "RB", "ADV"),
    "usually": ("d'habitude", "RB", "ADV"), "really": ("vraiment", "RB", "ADV"),
    "already": ("déjà", "RB", "ADV"), "still": ("encore", "RB", "ADV"),
    "never": ("jamais", "RB", "ADV"), "always": ("toujours", "RB", "ADV"),
    "sometimes": ("parfois", "RB", "ADV"), "now": ("maintenant", "RB", "ADV"),
    "then": ("alors", "RB", "ADV"), "here": ("ici", "RB", "ADV"),
    "there": ("là", "RB", "ADV"), "only": ("seulement", "RB", "ADV"),
    "just": ("juste", "RB", "ADV"), "even": ("même", "RB", "ADV"),
    "again": ("encore", "RB", "ADV"), "soon": ("bientôt", "RB", "ADV"),
    "later": ("plus tard", "RB", "ADV"), "today": ("aujourd'hui", "RB", "ADV"),
    "tomorrow": ("demain", "RB", "ADV"), "yesterday": ("hier", "RB", "ADV"),
    "immediately": ("immédiatement", "RB", "ADV"), "finally": ("enfin", "RB", "ADV"),
    "recently": ("récemment", "RB", "ADV"), "currently": ("actuellement", "RB", "ADV"),
    "previously": ("précédemment", "RB", "ADV"), "quickly": ("rapidement", "RB", "ADV"),
    "slowly": ("lentement", "RB", "ADV"), "easily": ("facilement", "RB", "ADV"),
    "hardly": ("à peine", "RB", "ADV"), "nearly": ("presque", "RB", "ADV"),
    "almost": ("presque", "RB", "ADV"), "quite": ("assez", "RB", "ADV"),
    "rather": ("plutôt", "RB", "ADV"), "probably": ("probablement", "RB", "ADV"),
    "certainly": ("certainement", "RB", "ADV"), "definitely": ("définitivement", "RB", "ADV"),
    "absolutely": ("absolument", "RB", "ADV"), "completely": ("complètement", "RB", "ADV"),
    "entirely": ("entièrement", "RB", "ADV"), "totally": ("totalement", "RB", "ADV"),
    "especially": ("surtout", "RB", "ADV"), "particularly": ("particulièrement", "RB", "ADV"),
    "simply": ("simplement", "RB", "ADV"), "merely": ("simplement", "RB", "ADV"),
    "mainly": ("principalement", "RB", "ADV"), "mostly": ("principalement", "RB", "ADV"),
    "largely": ("largement", "RB", "ADV"), "typically": ("typiquement", "RB", "ADV"),
    "generally": ("généralement", "RB", "ADV"), "normally": ("normalement", "RB", "ADV"),
    "actually": ("en fait", "RB", "ADV"), "basically": ("fondamentalement", "RB", "ADV"),
    "essentially": ("essentiellement", "RB", "ADV"), "widely": ("largement", "RB", "ADV"),
    "highly": ("hautement", "RB", "ADV"), "strongly": ("fortement", "RB", "ADV"),
    "deeply": ("profondément", "RB", "ADV"), "greatly": ("grandement", "RB", "ADV"),
    "mostly": ("principalement", "RB", "ADV"), "largely": ("largement", "RB", "ADV"),
    "mostly": ("principalement", "RB", "ADV"), "mostly": ("principalement", "RB", "ADV"),

    # ── Numbers & Quantifiers (30) ──────────────────────────────────
    "one": ("un", "CD", "NUM"), "two": ("deux", "CD", "NUM"),
    "three": ("trois", "CD", "NUM"), "four": ("quatre", "CD", "NUM"),
    "five": ("cinq", "CD", "NUM"), "six": ("six", "CD", "NUM"),
    "seven": ("sept", "CD", "NUM"), "eight": ("huit", "CD", "NUM"),
    "nine": ("neuf", "CD", "NUM"), "ten": ("dix", "CD", "NUM"),
    "hundred": ("cent", "CD", "NUM"), "thousand": ("mille", "CD", "NUM"),
    "million": ("million", "CD", "NUM"), "first": ("premier", "JJ", "ADJ"),
    "second": ("deuxième", "JJ", "ADJ"), "third": ("troisième", "JJ", "ADJ"),
    "last": ("dernier", "JJ", "ADJ"), "next": ("prochain", "JJ", "ADJ"),
    "half": ("moitié", "NN", "NC"), "quarter": ("quart", "NN", "NC"),
    "zero": ("zéro", "CD", "NUM"), "twenty": ("vingt", "CD", "NUM"),
    "thirty": ("trente", "CD", "NUM"), "forty": ("quarante", "CD", "NUM"),
    "fifty": ("cinquante", "CD", "NUM"), "sixty": ("soixante", "CD", "NUM"),
    "seventy": ("soixante-dix", "CD", "NUM"), "eighty": ("quatre-vingts", "CD", "NUM"),
    "ninety": ("quatre-vingt-dix", "CD", "NUM"),

    # ── Modal Verbs (10) ────────────────────────────────────────────
    "can": ("pouvoir", "MD", "V"), "could": ("pourrait", "MD", "V"),
    "will": ("sera", "MD", "V"), "would": ("voudrait", "MD", "V"),
    "shall": ("devra", "MD", "V"), "should": ("devrait", "MD", "V"),
    "may": ("peut", "MD", "V"), "might": ("pourrait", "MD", "V"),
    "must": ("doit", "MD", "V"), "ought": ("devrait", "MD", "V"),

    # ── Interrogatives & Relative (15) ──────────────────────────────
    "what": ("quoi", "WP", "PRO"), "who": ("qui", "WP", "PRO"),
    "whom": ("qui", "WP", "PRO"), "whose": ("dont", "WP$", "PRO"),
    "which": ("lequel", "WDT", "PRO"), "that": ("que", "WDT", "CON"),
    "this": ("ceci", "DT", "PRO"), "these": ("ceux-ci", "DT", "PRO"),
    "those": ("ceux-là", "DT", "PRO"),

    # ── Misc (20) ───────────────────────────────────────────────────
    "yes": ("oui", "UH", "INT"), "no": ("non", "UH", "INT"),
    "please": ("s'il vous plaît", "UH", "INT"), "thank": ("merci", "VB", "V"),
    "thanks": ("merci", "NNS", "NC"), "sorry": ("désolé", "JJ", "ADJ"),
    "hello": ("bonjour", "UH", "INT"), "bye": ("au revoir", "UH", "INT"),
    "welcome": ("bienvenue", "UH", "INT"), "ok": ("d'accord", "UH", "INT"),
    "well": ("bien", "RB", "ADV"), "just": ("juste", "RB", "ADV"),
    "thing": ("chose", "NN", "NC"), "lot": ("beaucoup", "NN", "NC"),
    "something": ("quelque chose", "NN", "NC"), "nothing": ("rien", "NN", "NC"),
    "everything": ("tout", "NN", "NC"), "anything": ("n'importe quoi", "NN", "NC"),
    "someone": ("quelqu'un", "NN", "NC"), "everyone": ("tout le monde", "NN", "NC"),
    "here": ("ici", "RB", "ADV"), "there": ("là-bas", "RB", "ADV"),
    "now": ("maintenant", "RB", "ADV"), "then": ("ensuite", "RB", "ADV"),
    "where": ("où", "WRB", "ADV"), "when": ("quand", "WRB", "ADV"),
    "why": ("pourquoi", "WRB", "ADV"), "how": ("comment", "WRB", "ADV"),
    "much": ("beaucoup", "RB", "ADV"), "many": ("beaucoup", "JJ", "ADJ"),
    "enough": ("assez", "RB", "ADV"), "such": ("tel", "JJ", "ADJ"),
    "own": ("propre", "JJ", "ADJ"), "else": ("autre", "RB", "ADV"),
    "ever": ("jamais", "RB", "ADV"), "yet": ("encore", "RB", "ADV"),
    "already": ("déjà", "RB", "ADV"), "even": ("même", "RB", "ADV"),
    "though": ("cependant", "IN", "CON"), "although": ("bien que", "IN", "CON"),
    "unless": ("sauf si", "IN", "CON"), "until": ("jusqu'à ce que", "IN", "CON"),
    "since": ("depuis que", "IN", "CON"), "while": ("tandis que", "IN", "CON"),
    "whether": ("si", "IN", "CON"), "after": ("après", "IN", "PRE"),
    "before": ("avant", "IN", "PRE"), "once": ("une fois", "IN", "CON"),

    # ── Computer Science Terms (150) ────────────────────────────────
    "algorithm": ("algorithme", "NN", "NC"), "algorithms": ("algorithmes", "NNS", "NC"),
    "data": ("données", "NNS", "NC"), "structure": ("structure", "NN", "NC"),
    "structures": ("structures", "NNS", "NC"), "variable": ("variable", "NN", "NC"),
    "variables": ("variables", "NNS", "NC"), "function": ("fonction", "NN", "NC"),
    "functions": ("fonctions", "NNS", "NC"), "class": ("classe", "NN", "NC"),
    "classes": ("classes", "NNS", "NC"), "object": ("objet", "NN", "NC"),
    "objects": ("objets", "NNS", "NC"), "method": ("méthode", "NN", "NC"),
    "methods": ("méthodes", "NNS", "NC"), "array": ("tableau", "NN", "NC"),
    "arrays": ("tableaux", "NNS", "NC"), "list": ("liste", "NN", "NC"),
    "lists": ("listes", "NNS", "NC"), "string": ("chaîne", "NN", "NC"),
    "strings": ("chaînes", "NNS", "NC"), "integer": ("entier", "NN", "NC"),
    "integers": ("entiers", "NNS", "NC"), "boolean": ("booléen", "NN", "NC"),
    "boolean": ("booléen", "NN", "NC"), "pointer": ("pointeur", "NN", "NC"),
    "pointers": ("pointeurs", "NNS", "NC"), "reference": ("référence", "NN", "NC"),
    "references": ("références", "NNS", "NC"), "memory": ("mémoire", "NN", "NC"),
    "stack": ("pile", "NN", "NC"), "queue": ("file", "NN", "NC"),
    "tree": ("arbre", "NN", "NC"), "trees": ("arbres", "NNS", "NC"),
    "graph": ("graphe", "NN", "NC"), "graphs": ("graphes", "NNS", "NC"),
    "node": ("nœud", "NN", "NC"), "nodes": ("nœuds", "NNS", "NC"),
    "edge": ("arête", "NN", "NC"), "edges": ("arêtes", "NNS", "NC"),
    "hash": ("hachage", "NN", "NC"), "table": ("table", "NN", "NC"),
    "tables": ("tables", "NNS", "NC"), "index": ("index", "NN", "NC"),
    "indexes": ("index", "NNS", "NC"), "database": ("base de données", "NN", "NC"),
    "databases": ("bases de données", "NNS", "NC"), "query": ("requête", "NN", "NC"),
    "queries": ("requêtes", "NNS", "NC"), "server": ("serveur", "NN", "NC"),
    "servers": ("serveurs", "NNS", "NC"), "client": ("client", "NN", "NC"),
    "clients": ("clients", "NNS", "NC"), "network": ("réseau", "NN", "NC"),
    "networks": ("réseaux", "NNS", "NC"), "protocol": ("protocole", "NN", "NC"),
    "protocols": ("protocoles", "NNS", "NC"), "socket": ("socket", "NN", "NC"),
    "sockets": ("sockets", "NNS", "NC"), "port": ("port", "NN", "NC"),
    "ports": ("ports", "NNS", "NC"), "thread": ("fil", "NN", "NC"),
    "threads": ("fils", "NNS", "NC"), "process": ("processus", "NN", "NC"),
    "processes": ("processus", "NNS", "NC"), "file": ("fichier", "NN", "NC"),
    "files": ("fichiers", "NNS", "NC"), "directory": ("répertoire", "NN", "NC"),
    "directories": ("répertoires", "NNS", "NC"), "folder": ("dossier", "NN", "NC"),
    "folders": ("dossiers", "NNS", "NC"), "path": ("chemin", "NN", "NC"),
    "module": ("module", "NN", "NC"), "modules": ("modules", "NNS", "NC"),
    "package": ("paquet", "NN", "NC"), "packages": ("paquets", "NNS", "NC"),
    "library": ("bibliothèque", "NN", "NC"), "libraries": ("bibliothèques", "NNS", "NC"),
    "framework": ("cadre", "NN", "NC"), "frameworks": ("cadres", "NNS", "NC"),
    "interface": ("interface", "NN", "NC"), "interfaces": ("interfaces", "NNS", "NC"),
    "abstract": ("abstrait", "JJ", "ADJ"), "concrete": ("concret", "JJ", "ADJ"),
    "inheritance": ("héritage", "NN", "NC"), "polymorphism": ("polymorphisme", "NN", "NC"),
    "encapsulation": ("encapsulation", "NN", "NC"), "recursion": ("récursion", "NN", "NC"),
    "iteration": ("itération", "NN", "NC"), "iterations": ("itérations", "NNS", "NC"),
    "loop": ("boucle", "NN", "NC"), "loops": ("boucles", "NNS", "NC"),
    "condition": ("condition", "NN", "NC"), "conditions": ("conditions", "NNS", "NC"),
    "exception": ("exception", "NN", "NC"), "exceptions": ("exceptions", "NNS", "NC"),
    "error": ("erreur", "NN", "NC"), "errors": ("erreurs", "NNS", "NC"),
    "debug": ("débogage", "NN", "NC"), "compiler": ("compilateur", "NN", "NC"),
    "compile": ("compiler", "VB", "V"), "executed": ("exécuté", "VBD", "V"),
    "runtime": ("exécution", "NN", "NC"), "syntax": ("syntaxe", "NN", "NC"),
    "semantic": ("sémantique", "JJ", "ADJ"), "parser": ("analyseur", "NN", "NC"),
    "token": ("jeton", "NN", "NC"), "tokens": ("jetons", "NNS", "NC"),
    "bytecode": ("bytecode", "NN", "NC"), "garbage": ("poubelle", "NN", "NC"),
    "collection": ("collecte", "NN", "NC"), "optimization": ("optimisation", "NN", "NC"),
    "optimizations": ("optimisations", "NNS", "NC"), "performance": ("performance", "NN", "NC"),
    "performances": ("performances", "NNS", "NC"), "complexity": ("complexité", "NN", "NC"),
    "sorting": ("tri", "NN", "NC"), "searching": ("recherche", "NN", "NC"),
    "merging": ("fusion", "NN", "NC"), "encoding": ("encodage", "NN", "NC"),
    "decoding": ("décodage", "NN", "NC"), "encryption": ("chiffrement", "NN", "NC"),
    "decryption": ("déchiffrement", "NN", "NC"), "compression": ("compression", "NN", "NC"),
    "bandwidth": ("bande passante", "NN", "NC"), "latency": ("latence", "NN", "NC"),
    "throughput": ("débit", "NN", "NC"), "concurrent": ("concournent", "JJ", "ADJ"),
    "parallel": ("parallèle", "JJ", "ADJ"), "asynchronous": ("asynchrone", "JJ", "ADJ"),
    "synchronous": ("synchrone", "JJ", "ADJ"), "callback": ("rappel", "NN", "NC"),
    "event": ("événement", "NN", "NC"), "events": ("événements", "NNS", "NC"),
    "handler": ("gestionnaire", "NN", "NC"), "handlers": ("gestionnaires", "NNS", "NC"),
    "observer": ("observateur", "NN", "NC"), "pattern": ("patron", "NN", "NC"),
    "patterns": ("patrons", "NNS", "NC"), "singleton": ("singleton", "NN", "NC"),
    "factory": ("usine", "NN", "NC"), "strategy": ("stratégie", "NN", "NC"),
    "adapter": ("adaptateur", "NN", "NC"), "decorator": ("décorateur", "NN", "NC"),
    "proxy": ("proxy", "NN", "NC"), "facade": ("façade", "NN", "NC"),
    "iterator": ("itérateur", "NN", "NC"), "composite": ("composite", "JJ", "ADJ"),
    "command": ("commande", "NN", "NC"), "state": ("état", "NN", "NC"),
    "template": ("modèle", "NN", "NC"), "visitor": ("visiteur", "NN", "NC"),
    "mediator": ("médiateur", "NN", "NC"), "memento": ("memento", "NN", "NC"),
    "null": ("nul", "JJ", "ADJ"), "void": ("vide", "JJ", "ADJ"),
    "return": ("retour", "NN", "NC"), "break": ("pause", "NN", "NC"),
    "continue": ("continuer", "VB", "V"), "switch": ("commutateur", "NN", "NC"),
    "default": ("défaut", "NN", "NC"), "try": ("essayer", "VB", "V"),
    "catch": ("attraper", "VB", "V"), "finally": ("finalement", "RB", "ADV"),
    "throw": ("lancer", "VB", "V"), "import": ("importer", "VB", "V"),
    "export": ("exporter", "VB", "V"), "require": ("nécessiter", "VB", "V"),
    "define": ("définir", "VB", "V"), "macro": ("macro", "NN", "NC"),
    "generic": ("générique", "JJ", "ADJ"), "type": ("type", "NN", "NC"),
    "types": ("types", "NNS", "NC"), "trait": ("trait", "NN", "NC"),
    "enum": ("énumération", "NN", "NC"), "struct": ("structure", "NN", "NC"),
    "union": ("union", "NN", "NC"), "implements": ("implémente", "VBZ", "V"),
    "extends": ("étend", "VBZ", "V"), "static": ("statique", "JJ", "ADJ"),
    "volatile": ("volatile", "JJ", "ADJ"), "const": ("constante", "NN", "NC"),
    "async": ("asynchrone", "JJ", "ADJ"), "await": ("attendre", "VB", "V"),
    "yield": ("rendre", "VB", "V"), "generator": ("générateur", "NN", "NC"),
    "protocol_proto": ("protocole", "NN", "NC"), "trait_proto": ("trait", "NN", "NC"),
    "mixin": ("mixin", "NN", "NC"),

    # ── Literary Terms (100) ────────────────────────────────────────
    "narrative": ("narratif", "JJ", "ADJ"), "protagonist": ("protagoniste", "NN", "NC"),
    "antagonist": ("antagoniste", "NN", "NC"), "plot": ("intrigue", "NN", "NC"),
    "theme": ("thème", "NN", "NC"), "themes": ("thèmes", "NNS", "NC"),
    "motif": ("motif", "NN", "NC"), "motifs": ("motifs", "NNS", "NC"),
    "symbol": ("symbole", "NN", "NC"), "symbols": ("symboles", "NNS", "NC"),
    "metaphor": ("métaphore", "NN", "NC"), "metaphors": ("métaphores", "NNS", "NC"),
    "simile": ("similitude", "NN", "NC"), "irony": ("ironie", "NN", "NC"),
    "satire": ("satire", "NN", "NC"), "allegory": ("allégorie", "NN", "NC"),
    "foreshadowing": ("anticipation", "NN", "NC"), "flashback": ("flashback", "NN", "NC"),
    "dialogue": ("dialogue", "NN", "NC"), "monologue": ("monologue", "NN", "NC"),
    "soliloquy": ("monologue intérieur", "NN", "NC"), "imagery": ("imagerie", "NN", "NC"),
    "tone": ("ton", "NN", "NC"), "style": ("style", "NN", "NC"),
    "genre": ("genre", "NN", "NC"), "novel": ("roman", "NN", "NC"),
    "novels": ("romans", "NNS", "NC"), "poem": ("poème", "NN", "NC"),
    "poems": ("poèmes", "NNS", "NC"), "essay": ("essai", "NN", "NC"),
    "essays": ("essais", "NNS", "NC"), "drama": ("drame", "NN", "NC"),
    "tragedy": ("tragédie", "NN", "NC"), "comedy": ("comédie", "NN", "NC"),
    "hero": ("héros", "NN", "NC"), "villain": ("méchant", "NN", "NC"),
    "conflict": ("conflit", "NN", "NC"), "conflicts": ("conflits", "NNS", "NC"),
    "resolution": ("résolution", "NN", "NC"), "climax": ("climax", "NN", "NC"),
    "exposition": ("exposition", "NN", "NC"), "narrator": ("narrateur", "NN", "NC"),
    "first_person": ("première personne", "NN", "NC"),
    "third_person": ("troisième personne", "NN", "NC"),
    "omniscient": ("omniscient", "JJ", "ADJ"), "unreliable": ("peu fiable", "JJ", "ADJ"),
    "reliable": ("fiable", "JJ", "ADJ"), "stream": ("flux", "NN", "NC"),
    "consciousness": ("conscience", "NN", "NC"), "epistolary": ("épistolaire", "JJ", "ADJ"),
    "gothic": ("gothique", "JJ", "ADJ"), "romantic": ("romantique", "JJ", "ADJ"),
    "realistic": ("réaliste", "JJ", "ADJ"), "modernist": ("moderniste", "JJ", "ADJ"),
    "postmodernist": ("postmoderniste", "JJ", "ADJ"), "existential": ("existentiel", "JJ", "ADJ"),
    "absurd": ("absurde", "JJ", "ADJ"), "dystopian": ("dystopique", "JJ", "ADJ"),
    "utopian": ("utopique", "JJ", "ADJ"), "parody": ("parodie", "NN", "NC"),
    "pastiche": ("pastiche", "NN", "NC"), "intertextuality": ("intertextualité", "NN", "NC"),
    "allusion": ("allusion", "NN", "NC"), "archetype": ("archétype", "NN", "NC"),
    "rhetoric": ("rhétorique", "NN", "NC"), "prose": ("prose", "NN", "NC"),
    "stanza": ("strophe", "NN", "NC"), "verse": ("vers", "NN", "NC"),
    "rhyme": ("rime", "NN", "NC"), "meter": ("mètre", "NN", "NC"),
    "alliteration": ("allitération", "NN", "NC"), "assonance": ("assonance", "NN", "NC"),
    "consonance": ("consonance", "NN", "NC"), "enjambment": ("enjambement", "NN", "NC"),
    "caesura": ("césure", "NN", "NC"), "anaphora": ("anaphore", "NN", "NC"),
    "epistrophe": ("épistrophe", "NN", "NC"), "chiasmus": ("chiasme", "NN", "NC"),
    "antithesis": ("antithèse", "NN", "NC"), "parallelism": ("parallélisme", "NN", "NC"),
    "hyperbole": ("hyperbole", "NN", "NC"), "litotes": ("litote", "NN", "NC"),
    "euphemism": ("euphémisme", "NN", "NC"), "oxymoron": ("oxymore", "NN", "NC"),
    "paradox": ("paradoxe", "NN", "NC"), "personification": ("personnification", "NN", "NC"),
    "synecdoque": ("métonymie", "NN", "NC"), "metonymy": ("métonymie", "NN", "NC"),

    # ── Scientific / Academic Terms (50) ────────────────────────────
    "research": ("recherche", "NN", "NC"), "hypothesis": ("hypothèse", "NN", "NC"),
    "hypotheses": ("hypothèses", "NNS", "NC"), "experiment": ("expérience", "NN", "NC"),
    "experiments": ("expériences", "NNS", "NC"), "theory": ("théorie", "NN", "NC"),
    "theories": ("théories", "NNS", "NC"), "evidence": ("preuve", "NN", "NC"),
    "evidences": ("preuves", "NNS", "NC"), "analysis": ("analyse", "NN", "NC"),
    "analyses": ("analyses", "NNS", "NC"), "methodology": ("méthodologie", "NN", "NC"),
    "conclusion": ("conclusion", "NN", "NC"), "conclusions": ("conclusions", "NNS", "NC"),
    "abstract": ("résumé", "NN", "NC"), "introduction": ("introduction", "NN", "NC"),
    "discussion": ("discussion", "NN", "NC"), "results": ("résultats", "NNS", "NC"),
    "findings": ("conclusions", "NNS", "NC"), "literature": ("littérature", "NN", "NC"),
    "review": ("revue", "NN", "NC"), "citation": ("citation", "NN", "NC"),
    "citations": ("citations", "NNS", "NC"), "bibliography": ("bibliographie", "NN", "NC"),
    "appendix": ("annexe", "NN", "NC"), "figure": ("figure", "NN", "NC"),
    "figures": ("figures", "NNS", "NC"), "equation": ("équation", "NN", "NC"),
    "equations": ("équations", "NNS", "NC"), "formula": ("formule", "NN", "NC"),
    "formulas": ("formules", "NNS", "NC"), "proof": ("preuve", "NN", "NC"),
    "theorem": ("théorème", "NN", "NC"), "theorems": ("théorèmes", "NNS", "NC"),
    "lemma": ("lemme", "NN", "NC"), "corollary": ("corollaire", "NN", "NC"),
    "definition": ("définition", "NN", "NC"), "definitions": ("définitions", "NNS", "NC"),
    "axiom": ("axiome", "NN", "NC"), "axioms": ("axiomes", "NNS", "NC"),
    "proposition": ("proposition", "NN", "NC"), "conjecture": ("conjecture", "NN", "NC"),
    "model": ("modèle", "NN", "NC"), "models": ("modèles", "NNS", "NC"),
    "simulation": ("simulation", "NN", "NC"), "validation": ("validation", "NN", "NC"),
    "verification": ("vérification", "NN", "NC"), "accuracy": ("précision", "NN", "NC"),
    "precision": ("exactitude", "NN", "NC"), "recall": ("rappel", "NN", "NC"),
    "benchmark": ("référence", "NN", "NC"), "benchmarks": ("références", "NNS", "NC"),
    "dataset": ("jeu de données", "NN", "NC"), "training": ("entraînement", "NN", "NC"),
    "testing": ("test", "NN", "NC"), "validation": ("validation", "NN", "NC"),
    "overfitting": ("surapprentissage", "NN", "NC"), "underfitting": ("sous-apprentissage", "NN", "NC"),
    "regularization": ("régularisation", "NN", "NC"), "bias": ("biais", "NN", "NC"),
    "variance": ("variance", "NN", "NC"), "noise": ("bruit", "NN", "NC"),
    "signal": ("signal", "NN", "NC"), "feature": ("caractéristique", "NN", "NC"),
    "features": ("caractéristiques", "NNS", "NC"), "extraction": ("extraction", "NN", "NC"),
    "selection": ("sélection", "NN", "NC"), "engineering": ("ingénierie", "NN", "NC"),
    "dimensionality": ("dimensionnalité", "NN", "NC"), "reduction": ("réduction", "NN", "NC"),
    "clustering": ("clustering", "NN", "NC"), "classification": ("classification", "NN", "NC"),
    "regression": ("régression", "NN", "NC"), "supervised": ("supervisé", "JJ", "ADJ"),
    "unsupervised": ("non supervisé", "JJ", "ADJ"), "reinforcement": ("renforcement", "NN", "NC"),
    "neural": ("neuronal", "JJ", "ADJ"), "network": ("réseau", "NN", "NC"),
    "networks": ("réseaux", "NNS", "NC"), "layer": ("couche", "NN", "NC"),
    "layers": ("couches", "NNS", "NC"), "neuron": ("neurone", "NN", "NC"),
    "neurons": ("neurones", "NNS", "NC"), "weight": ("poids", "NN", "NC"),
    "weights": ("poids", "NNS", "NC"), "activation": ("activation", "NN", "NC"),
    "loss": ("perte", "NN", "NC"), "gradient": ("gradient", "NN", "NC"),
    "descent": ("descente", "NN", "NC"), "backpropagation": ("rétropropagation", "NN", "NC"),
    "convolution": ("convolution", "NN", "NC"), "pooling": ("pooling", "NN", "NC"),
    "recurrent": ("récurrent", "JJ", "ADJ"), "attention": ("attention", "NN", "NC"),
    "transformer": ("transformateur", "NN", "NC"), "encoder": ("encodeur", "NN", "NC"),
    "decoder": ("décodeur", "NN", "NC"), "embedding": ("intégration", "NN", "NC"),
    "vocabulary": ("vocabulaire", "NN", "NC"), "tokenization": ("tokenisation", "NN", "NC"),
    "batch": ("lot", "NN", "NC"), "epoch": ("époque", "NN", "NC"),
    "learning": ("apprentissage", "NN", "NC"), "rate": ("taux", "NN", "NC"),
    "optimizer": ("optimiseur", "NN", "NC"), "dropout": ("abandon", "NN", "NC"),
    "batchnorm": ("normalisation par lot", "NN", "NC"),
    "relu": ("relu", "NN", "NC"), "sigmoid": ("sigmoïde", "NN", "NC"),
    "softmax": ("softmax", "NN", "NC"), "tanh": ("tanh", "NN", "NC"),

    # ── Coffee-related terms (missing from original) ────────────────
    "seeds": ("graines", "NNS", "NC"), "berries": ("baies", "NNS", "NC"),
    "plant": ("plante", "NN", "NC"), "plants": ("plantes", "NNS", "NC"),
    "flavor": ("saveur", "NN", "NC"), "flavors": ("saveurs", "NNS", "NC"),
    "cultivation": ("cultivation", "NN", "NC"), "origins": ("origines", "NNS", "NC"),
    "highlands": ("hauteurs", "NNS", "NC"), "legend": ("légende", "NN", "NC"),
    "goat": ("chèvre", "NN", "NC"), "herder": ("berger", "NN", "NC"),
    "effects": ("effets", "NNS", "NC"), "journey": ("voyage", "NN", "NC"),
    "bean": ("grosse", "NN", "NC"), "beans": ("gros", "NNS", "NC"),
    "cup": ("tasse", "NN", "NC"), "harvesting": ("récolte", "NN", "NC"),
    "cherries": ("cerises", "NNS", "NC"), "sun": ("soleil", "NN", "NC"),
    "quality": ("qualité", "NN", "NC"), "brown": ("brun", "JJ", "ADJ"),
    "compounds": ("composés", "NNS", "NC"), "reactions": ("réactions", "NNS", "NC"),
    "roast": ("torréfaction", "NN", "NC"), "shot": ("extraction", "NN", "NC"),
    "layer": ("couche", "NN", "NC"), "crema": ("crème", "NN", "NC"),
    "bed": ("lit", "NN", "NC"), "metal": ("métal", "NN", "NC"),
    "filter": ("filtre", "NN", "NC"), "grounds": (" marc", "NNS", "NC"),
    "sediment": ("sédiment", "NN", "NC"), "culture": ("culture", "NN", "NC"),
    "foundation": ("fondation", "NN", "NC"), "traditions": ("traditions", "NNS", "NC"),
    "countries": ("pays", "NNS", "NC"), "breaks": ("pauses", "NNS", "NC"),
    "institution": ("institution", "NN", "NC"), "bottom": ("fond", "NN", "NC"),
    "scene": ("scène", "NN", "NC"), "industry": ("industrie", "NN", "NC"),
    "challenges": ("défis", "NNS", "NC"), "prices": ("prix", "NNS", "NC"),
    "trade": ("commerce", "NN", "NC"), "initatives": ("initiatives", "NNS", "NC"),
    "producers": ("producteurs", "NNS", "NC"), "practices": ("pratiques", "NNS", "NC"),
    "farming": ("agriculture", "NN", "NC"), "impact": ("impact", "NN", "NC"),
    "method": ("méthode", "NN", "NC"), "methods": ("méthodes", "NNS", "NC"),
    "press": ("presse", "NN", "NC"), "craft": ("artisanat", "NN", "NC"),
    "climate": ("climat", "NN", "NC"), "sustainability": ("durabilité", "NN", "NC"),
    "biodiversity": ("biodiversité", "NN", "NC"), "preparation": ("préparation", "NN", "NC"),
    "social": ("social", "JJ", "ADJ"), "specialty": ("spécialité", "NN", "NC"),
}
