micronaut:
  application:
    name: ppois4
  views:
    enabled: true
    thymeleaf:
      enabled: true
      prefix: classpath:views/
      suffix: .html
  session:
    max-inactive-interval: 30s
  server:
    port: 8001