micronaut:
  application:
    name: ppois4
  scan:
    packages: by.romanov.ppois.webapp
  views:
    enabled: true
    thymeleaf:
      enabled: true
      prefix: classpath:views/
      suffix: .html
  session:
    max-inactive-interval: 30s
  server:
    port: 8001
logging:
  level:
    root: DEBUG
    io.micronaut: DEBUG
    org.thymeleaf: DEBUG